drop table if exists item CASCADE;
create table item
(
    -- identity 전략이고 하는데, 기본 키 생성을 데이터베이스에 위임하는 방법이다.
    -- MySQL의 AutoIncrement와 같은 방법이다.
    id        bigint generated by default as identity,
    item_name varchar(10),
    price     integer,
    quantity  integer,
    primary key (id)
);
